name = "ffep-v2-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
SMARTY_KEY = "YOUR_SMARTY_KEY"
SMARTY_WEBSITE_KEY = "YOUR_SMARTY_WEBSITE_KEY"

# Add your environment-specific variables here
[env.production]
routes = [
  { pattern = "point.com/api/ffep/*", zone_id = "YOUR_ZONE_ID" }
]

[env.staging]
routes = [
  { pattern = "staging.point.com/api/ffep/*", zone_id = "YOUR_ZONE_ID" }
] 